import { Input } from "@/components/ui/input";
import { ScrollArea,ScrollBar } from "@/components/ui/scroll-area";
import { Textarea } from "@/components/ui/textarea";
import { UiContext } from "@/context/UiProvider";
import { AudioLines, Paperclip, Send} from "lucide-react";
import Image from "next/image";
import { useContext } from "react";
const Home = () => {
  const {isSidebarOpen} = useContext(UiContext);
  console.log(isSidebarOpen)
  return (
    <>
      {/* Chat container */}
      <div className="mx-auto w-full md:w-3xl 2xl:w-4xl flex flex-col gap-10">
        {/* Message */}
        <div className="w-full">
          <div className="h-92 overflow-y-auto border  p-3 space-y-2 w-full">
            <div className="my-5 ">
              <div className="font-medium text-center flex gap-2 justify-center">
                {" "}
                <Image src="logo.svg" width={25} height={25} alt="" />
                <h3 className="text-2xl font-medium">Hi ! This is EchoGPT </h3>
              </div>
              <p className=" text-center">How can i help you?</p>
            </div>
          </div>
        </div>

        {/* Input field */}
        <div className=" border rounded-md p-2">
         
        <Textarea
  className="w-full resize-none border-none max-h-24  scrollbar-none pb-1"
  placeholder="Ask me anything..."
  style={{
    fontSize: "16px",
    scrollbarColor: " blue", // Firefox
   
  }}
/>

         
          <div className=" flex justify-between gap-2 px-2 pt-2 w-full bottom-1">
            
            <label
              htmlFor="file-upload"
              className=" bottom-4 left-4 cursor-pointer text-gray-600"
            >
              <Paperclip size={24} />
            </label>
            <Input type="file" id="file-upload" className="hidden" />

           <div className="flex gap-2 items-center">
           <label
              htmlFor="file-upload"
              className=" bottom-4 left-4 cursor-pointer text-gray-600"
            >
              <AudioLines size={24} />
            </label>
            <Input type="file" id="file-upload" className="hidden" />
            <Send className=" " />
           </div>
          </div>
        </div>
        <div>
          <p className="text-center">Generated by AI</p>
        </div>
      </div>
    </>
  );
};

export default Home;
